name: playx_navigation
description: Playx Navigation is a Flutter package that enhances app navigation with advanced features like route lifecycle management, custom transitions, and flexible configuration.
version: 0.2.0
homepage: https://sourcya.io
repository: https://github.com/playx-flutter/playx_navigation
issue_tracker: https://github.com/playx-flutter/playx_navigation/issues
topics:
  - playx
  - navigation
  - deep-linking
  - go-router
  - route-management

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.27.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^16.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

