name: playx_navigation
description: Playx Navigation is a Flutter package that enhances app navigation with advanced features like route lifecycle management, custom transitions, and flexible configuration.
version: 0.0.1
homepage: https://github.com/playx-flutter/playx_navigation
repository: https://github.com/playx-flutter/playx_navigation
issue_tracker: https://github.com/playx-flutter/playx_navigation/issues
topics:
  - playx
  - navigation
  - go_router

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
