name: playx_navigation
description: Playx Navigation is a Flutter package that enhances app navigation with advanced features like route lifecycle management, custom transitions, and flexible configuration.
version: 0.1.1
homepage: https://sourcya.io
repository: https://github.com/playx-flutter/playx_navigation
issue_tracker: https://github.com/playx-flutter/playx_navigation/issues
topics:
  - playx
  - navigation
  - deep-linking
  - go-router
  - route-management

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"


dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

